dist: xenial
language: node_js
node_js:
  - 10

addons:
  firefox: "latest"
  chrome: "stable"

before_script:
  - yarn

stages:
  - build
  - check
  - test

jobs:
  include:
    - stage: build
      name: Make sure the build is successful
      script:
        - yarn build

    - stage: check
      name: Audit package dependencies for security vulnerabilities
      script: yarn audit

    - stage: test
      before_script:
      name: "Run linter (ESLint)"
      script: yarn lint

    - name: Run karma test suite
      script: yarn test
      before_script:
        - "Xvfb :99 & export DISPLAY=:99"
        - sleep 5

