dist: xenial
language: node_js
node_js:
  - 10
# stages:
#   - build
#   - check
#   - test
jobs:
  include:
    - stage: "Build"
      name: Make sure the build is successful
      script: yarn build

    - stage: "Check"
      name: Audit package dependencies for security vulnerabilities
      script: yarn audit

    - name: Run linter (ESLint)
      script: yarn lint
  
    - stage: "Test"
      name: Run karma test suite
      addons:
        firefox: latest
        chrome: stable
      script:
        - yarn build
        - yarn test
      before_script:
        - Xvfb :99 & export DISPLAY=:99
        - sleep 5
    
    - stage: "Deploy"
      name: "Deploy to NPM JS"
      if: tag IS present
      script: skip
      before_deploy:
        - yarn build
      deploy:
        provider: script
        on:
          tags: true
          branch: ci-fixes
        skip_cleanup: true
        script:
          - npx semantic-release
